FROM ad/jenkins-debian-glue-builder:latest
MAINTAINER André Draszik "git@andred.net"

# add prebuilt cowbuilder/pbuilder chroots
ADD base-sid-amd64.cow.tar.xz /var/cache/pbuilder/
ADD base-sid-armel.cow.tar.xz /var/cache/pbuilder/

#USER user
